# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=40, null=True)),
                ('faculty', models.CharField(blank=True, max_length=40, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=20, null=True)),
                ('is_paying_member', models.BooleanField(default=True)),
                ('day_of_signup', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
